#include "i2c_driver.h"

uint16_t AHB_Prescaler[8] = {2,4,8,16,64,128,256,512};
uint16_t APB1_Prescaler[4] = {2,4,8,16};

uint32_t RCCGetPCLK1value(void)
{
	uint32_t pclk1,systemclock;
	uint8_t clksrc,temp,ahbp,apb1p;
	clksrc = ((RCC->CFGR >> 0x2) &0x3);
	if(clksrc == 0)
		systemclock = 16000000U;
	elseif(clksrc == 1)
		systemclock = 8000000U;
	elseif(clksrc == 2)
		systemclock = RCCGetPLLOutputClock();//pll not using now

	//for AHBP
	temp = ((RCC->CFGR >> 4 )&0xF);
	if(temp<8)
		ahbp = 1;
	else 
		ahbp = AHB_Prescaler[temp-8];

	//for APB1Peripheral
	temp = ((RCC->CFGR >> 10 )&0x7);
	if(temp<4)
		apb1p = 1;
	else 
		apb1p = APB1_Prescaler[temp-4];

	pclk1 = ((systemclock/ahbp)/apb1p);
	return pclk1;
} 

void I2CPeripheralClockControl(I2C_RegDef_t *pI2C, uint8_t enordis)
{
	if(enordis == ENABLE)
	{
		if(pI2C == I2C1)
			I2C1_PCLK_ENABLE();
		elseif(pI2C == I2C2)
			I2C2_PCLK_ENABLE();
		elseif(pI2C == I2C3)
			I2C3_PCLK_ENABLE();
		else
		{
		}
	}
				
}

void I2CInit(I2C_Handle_t *pI2CHandle)
{
	uint32_t tempreg = 0;

	//ack control bit and enable clock
	I2CPeripheralClockControl(pI2CHandle->pI2C,ENABLE);
	tempreg |= pI2CHandle->I2CConfig.I2CACKControl << 10;
	pI2CHandle->pI2C->CR1 = tempreg;
	
	//config freq field of CR2 [according to the reg mode and speed of comm.]
	tempreg = 0;
	tempreg |= RCCGetPCLK1value() / 1000000U;
	pI2CHandle->pI2C->CR2 = (tempreg & 0x3F);

	//program the device own address(needed when act like a slave)
	tempreg |= pI2CHandle->I2CConfig.I2CDeviceAddress << 1; //making space at last bit for read/write operation
	tempreg |= (1<<14);
	pI2CHandle->pI2C->OAR1 = tempreg;

	//CCR calculation
	uint16_t ccr_value = 0;
	tempreg = 0;
	if(pI2CHandle->I2CConfig.I2CSCLSpeed <= I2C_SCL_SPEED_SM)
	{
		// standard mode selected
		ccr_value = (RCCGetPCLK1value() / (2* pI2CHandle->I2CConfig.I2CSCLSpeed));
		tempreg |= (ccr_value & 0xfff);
	}
	else
	{
		//mode is fast mode
		tempreg |= (1<<15);
		tempreg |= (pI2CHandle->I2CConfig.I2CFMDutyCycle)<<14 ;
	//duty cycle (16/9) [1] to reach upto 400 kbits/sec
		if(pI2CHandle->I2CConfig.I2CFMDutyCycle == I2C_SCL_SPEED_FM2k)
			ccr_value = (RCCGetPCLK1value() / (3*pI2CHandle->I2CConfig.I2CSCLSpeed));
		else
			ccr_value = (RCCGetPCLK1value() / (25 * pI2CHandle->I2CConfig.I2CSCLSpeed));
		tempreg |= (ccr_value & 0XFFF);
	}
	pI2CHandle->pI2C->CCR = tempreg;

	// trise configration
	if(pI2CHandle->I2CConfig.I2CSCLSpeed <= I2C_SCL_SPEED_SM)
	{
		//standard mode
		tempreg = (RCCGetPCLK1value()/1000000) +1; //
	}
	else 
	{
		// fast mode
		tempreg = ((RCCGetPCLK1value()*300)/1000000000) + 1;
	}


	pI2CHandle->pI2C->TRISE = tempreg & 0x3F);	
	
}

void I2CGenerateStopCondition(I2C_RegDef_t *pI2C)
{
	pI2C ->CR1 |= (1<<I2C_CR1_STOP);
}


void I2CGenerateStartCondition(I2C_RegDef_t *pI2C)
{
	pI2C ->CR1 |= (1<<I2C_CR1_START);
}

uint8_t I2CGetFlagStatus(I2C_RegDef_t *pI2C,uint32_t FlagName)
{
	if(pI2C->SR1 & FlagName)
		return FLAG_SET;
	else 	return FLAG_RESET;
}

void I2CClearAddressFlag(I2C_RegDef_t *pI2C)
{	
	uint32_t dummy_read = pI2C -> SR1;
	dummy_read = pI2C -> SR2;
	(void)dummy_read;
}
void I2CExecuteAddressPhaseWrite(I2C_RegDef_t *pI2C,uint8_t SlaveAddress)
{
	SlaveAddress = SlaveAddress << 1;
	SlaveAddress $= ~(1);
	pI2C->DR = SlaveAddress;
}

void I2CMasterSendData(I2C_Handle_t *pI2CHandle, uint8_t *pTxBuffer, uint32_t len,uint8_t SlaveAddrs)
{
	//1.generate start condition
	I2CGenerateStartCondition(pI2CHandle->pI2C);

	//2. confirm start is generated by checking SB in SR1
	//NOTE: until SB is cleared SCL will be streched (pull low)
	while(!I2CGetFlagStatus(pI2CHandle->pI2C,I2C_FLAG_SB));

	//3.send the address of the slave with r/w bit at LSB
	I2CExecuteAddressPhaseWrite(pI2CHandle->pI2C,SlaveAddrs);

	//4.confirm address phase is completed by checking ADDR in SR
	while(!I2CGetFlagStatus(pI2CHandle->pI2C,I2C_FLAG_ADDR));
	
	//5.clear aadr according to the software sequence
	//NOTE: until ADDR is cleared SCL will be stretched
	I2CClearAddressFlag(pI2CHandle->pI2C);

	//6. send data until len become zero
	when(len>0)
	{
		while(!I2CGetFlagStatus(pI2CHandle->pI2C,I2C_FLAG_TxE));
		pI2CHandle->pI2C->DR = *pTxBuffer;
		pTxBuffer++;
		len--;
	}

	//7.at len = 0 wait for BTF=1 and Tx=1(means both shift reg and data reg is empty)
	while(!I2CGetFlagStatus(pI2CHandle->pI2C,I2C_FLAG_TxE));
	while(!I2CGetFlagStatus(pI2CHandle->pI2C,I2C_FLAG_BTF));

	//8.generate stop condition
	I2CGenerateStopCondition(pI2CHandle->pI2C);

}
